### ISSUE TITLE
cleaning up the whole project dir could be good 

### ISSUE THREAD

**Issue by koji** [trafalmejo/OSCAR#2]
There some unnecessary files like `dist/fonts`, `.DS_Store`, `index.md` and so on.

Probably you need to update `.gitignore` then you can solve most of them.

also recommend you to use https://semver.org/ for versioning since this is the de facto standard and inexpensive.

**Comment by trafalmejo** [comment]
Hi Koji,
Thanks for your input. I am taking care of those files to clean up the project. Thanks again.

**Comment by koji** [comment]
@trafalmejo seems @montoyamoraga removed `.DS_Store` files
great job @montoyamoraga

**Comment by montoyamoraga** [comment]
i vote yes npm, no yarn,
and closing this issue :)
