### ISSUE TITLE
Import and export formats don't match

### ISSUE THREAD

**Issue by jamshark70** [trafalmejo/OSCAR#9]
Using the v1.0 release:

- Export presents you with HTML and CSS as separate documents.

- Import expects a single HTML document.

In order to import a page that you had saved previously, you have to hand-edit the HTML to embed the CSS in `<style>...</style>` tags. Which is... inconvenient.

Shouldn't the export button give you text that you can simply paste into the import panel?

**Comment by trafalmejo** [comment]
That's correct. Persistence (saving and loading) is something I am working on.
Something you can do to export is to copy the data you find in the import modal and paste it into a text file and save independently. Then you can import this same content without editing. This method is also inconvenient and does not save the values for IPs, ports, and addresses you set up for your components.

In the next release, I will remove the export functionality. Instead, OSCAR will implement save and load buttons to keep the OSCAR server running. This way you will have also access to the same interfaces from all devices connected to the same network

**Comment by jamshark70** [comment]
> In the next release, I will remove the export functionality. Instead, OSCAR will implement save and load buttons to keep the OSCAR server running.

Right, if there's no fix to persist the OSC settings in the HTML export, then it's better to find another mechanism.

Will this allow saving different interfaces under different names, or is it only to persist the current document in the server? If, for example, I wanted to use it in a class and let the students design interfaces, could they save the interface and then send me a package that I could load on my machine?

This would also be useful for work-for-hire where you might have to switch between projects, and at the end provide a deliverable to a client.

**Comment by trafalmejo** [comment]
You will able to save files with different names and load them when you need them. You will also have the ability to share designs with a link, and manage your projects.
